name: xml2json
version: 6.1.0
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
repository: https://github.com/shamblett/xml2json
homepage: https://github.com/shamblett/xml2json

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xml: '^6.3.0'

dev_dependencies:
  test: '^1.24.2'
  pedantic: '^1.10.0'
  lints: '^2.1.0'
  build_runner: '^2.4.2'
  build_test: '^2.1.7'
  build_web_compilers: '^4.0.3'
